{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggseqlogo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggseqlogo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggseqlogo/ggseqlogo_{{ version }}.tar.gz
  sha256: 28a5d9b728a2155c0869200ed426e4b2cb7b768d98d801fce46b6360c9eb2d08

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('ggseqlogo')"           # [not win]
    - "\"%R%\" -e \"library('ggseqlogo')\""  # [win]

about:
  home: https://github.com/omarwagih/ggseqlogo
  license: LGPL-2.0-or-later
  summary: The extensive range of functions provided by this package makes it possible to draw highly versatile sequence logos. Features include, but not limited to, modifying colour schemes and fonts used to draw the logo, generating multiple logo plots, and aiding the visualisation with annotations. Sequence logos can
    easily be combined with other plots 'ggplot2' plots.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
