# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DYfE0bmdvuNihbecVY04EuaQJebEH+qpAbaxjOqMr2gtloEAre4pfb/rUD116klUR8V7AniSbkmes05UDspAWwHRhGlKT9vKtgQQX/9acjATBVY6lhuPhYVfBdSNZp6Q9TfAxEzySKb5yqJvkxFeHCGHRWQxEDStCTHkaue9rtBaovk9Gh/WEVi8mjB4KnHfSeTHB7/3Y0K4XPB5D3DJbgfcOcqL7kFpn1Zvwps1RizQ4a3AR/XD3wdY9qwf05nNvtd+vXTRJg8agmVD7b/xnMA5wxvFsfRT5g3yL0HXhvf7z8+oj8XzLlyhSKWQpKpMV+sTzrCvHWSaN7yTaEplnarC4Twp8zIzZ4ihT3StuM2kI1jWhr2PH19WOvDRe33ERO2S7ugBjmHmwZI0s8gBn7FXacpNOHvR+U1ZJDeuJMaUaEiwn4ie8oTrGxDVhVC1CmUlTPLJVGDRLifDVX4tjs47HjUcTe54ETjYOOhKm8DU9zrYcadt1qvAYkpeiN8X4SBJObxMZ6R7osVCbL4qIaUys+OuJ1VpaF0Bl7Yz929SgXeYDHLEAYN2UMsjsm5/FrZM+L/OJFJ9uvC33+rsQagoxxkXDemrErKhb52USw9cFyGGANm5kmtxJOT59tkf4+IT5lT6K1Oxe0UKBfx/Mb9DYaODi11vsyFaOQF7FOg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
