travis:
  secure:
    BINSTAR_TOKEN: pFBF0gqAf2OMNJwvfHNK/ZjvYQUntzhmauer+qFoA89E9lMg+xM5w3TygwHy1VlvroRpQPrILZgO/dZ9FkZ77vbnlXhE/qWusSpERHlJPOVXLMX/aMNqkFviTqNnDqoJxTyCAEMRvBgumY0uhHZ8Vz6Mwy7tWCEjBupWs+zUgZqoN7kjwS87WVy2vx8d17wDa7tWtVc5NYI07qtWTTw9y1++1oORUKcqrY02hLTQGd53hwMJBNjsLdkLgShNQvmG5Q3G7dy7TOhrHPRpN35EGiCGiUzRR+xSthoF/ZjvdcH5maBEwhcuYfsIkkEPp1ItR024hvh2Pxb2Frlx2XFYpiMMMzlfJFA9nIaCNyzecZCBSs/tq+9ETqB757E5T+VlgIDaLY4d6/YX3n/yscfvdKafGDDEUFErfxf+V7EO8XGUadRiBQPfTaAdxqpoPq2pkaNiSWFXEQ40tJIXazRXxOiRYeoY98qdmfu7lLTWljesN9CXKbEK0aRXAjCIku3nb5yXMfBftNttfGeF8ol6qkshqZvQyMkrjbscSGUdeJTxqaX7rPcv2tnMvVdoQ2vlow3vysWR3vmD3oxGcnVxM7Y3eKL9SXkIvmfdKFhe8ijgTXd4fav82tIGuQoNkAPD+YbZ1FVHmjZioOWsHrCmTURC5XYzwKQ+vH3RpGlL/y0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
